# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zu7ELsBZbAvYvjozOKazbnvuR0vCXjAt
"""

import nest_asyncio
nest_asyncio.apply()

import asyncio

async def download_file(file_name, delay):
    print(f"Iniciando la descarga de {file_name}...")
    await asyncio.sleep(delay)
    print(f"Descarga de {file_name} Descarga completada!")

async def main():
    tasks = [
        download_file("archivo1.txt", 2),
        download_file("archivo2.txt", 3),
        download_file("archivo3.txt", 1)
    ]
    await asyncio.gather(*tasks)

if __name__ == '__main__':
    asyncio.run(main())